#pragma once
#include <EdkMdb.h>
#define MAPI_FORCE_ACCESS 0x00080000
#define PR_EMSMDB_SECTION_UID					PROP_TAG(PT_BINARY, 0x3D15)
#define PR_PROFILE_USER_SMTP_EMAIL_ADDRESS		PROP_TAG(PT_STRING8, pidProfileMin+0x41)
#define PR_PROFILE_USER_SMTP_EMAIL_ADDRESS_W	PROP_TAG(PT_UNICODE, pidProfileMin+0x41)
#define PR_ROH_PROXY_SERVER						PROP_TAG(PT_UNICODE, pidProfileMin+0x22)
#define PR_PROFILE_RPC_PROXY_SERVER_FLAGS		PROP_TAG(PT_LONG,	pidProfileMin+0x23)
#define PR_ROH_PROXY_PRINCIPAL_NAME				PROP_TAG( PT_UNICODE, pidProfileMin+0x25)
#define PR_PROFILE_RPC_PROXY_SERVER_AUTH_PACKAGE	PROP_TAG(PT_LONG,	pidProfileMin+0x27)
#define PR_PROFILE_RPC_PROXY_SERVER_W			PROP_TAG( PT_UNICODE, pidProfileMin+0x22)
#define PR_PROFILE_HOME_SERVER_FQDN				PROP_TAG(PT_UNICODE, pidProfileMin+0x2A)
#define	PR_PROFILE_SERVER_FQDN_W				PROP_TAG( PT_UNICODE, pidProfileMin+0x2b)
#define PR_PROFILE_ACCT_NAME					PROP_TAG( PT_STRING8, pidProfileMin+0x20)  
#define PR_PROFILE_ACCT_NAME_W					PROP_TAG( PT_UNICODE, pidProfileMin+0x20) 
#define PR_PROFILE_USER_EMAIL_W					PROP_TAG(PT_UNICODE, pidProfileMin+0x3d) 
#define PR_PROFILE_DISPLAYNAME_SET		PROP_TAG( PT_LONG, pidSpecialMin+0x18)
#define	PR_PROFILE_UNRESOLVED_NAME_W			PROP_TAG( PT_UNICODE, pidProfileMin+0x07)  
#define PR_PROFILE_UNRESOLVED_SERVER_W	PROP_TAG( PT_UNICODE, pidProfileMin+0x08)
#define PR_PROFILE_OFFLINE_STORE_PATH_W	PROP_TAG( PT_UNICODE, pidProfileMin+0x10) 
#define PR_PROFILE_LKG_AUTODISCOVER_URL			PROP_TAG(PT_UNICODE, pidProfileMin+0x4A)
#define	PR_PROFILE_SERVER_FQDN				PROP_TAG( PT_UNICODE, pidProfileMin+0x2b)
#define PR_PROFILE_MAPIHTTP_MAILSTORE_INTERNAL_URL PROP_TAG(PT_UNICODE, pidProfileMin+0x52)
#define PR_PROFILE_MAPIHTTP_MAILSTORE_EXTERNAL_URL PROP_TAG(PT_UNICODE, pidProfileMin+0x53)
#define PR_PROFILE_MAPIHTTP_ADDRESSBOOK_INTERNAL_URL PROP_TAG(PT_UNICODE, pidProfileMin+0x54)
#define PR_PROFILE_MAPIHTTP_ADDRESSBOOK_EXTERNAL_URL PROP_TAG(PT_UNICODE, pidProfileMin+0x55)
#define	PR_PROFILE_HOME_SERVER_FQDN_W			PROP_TAG( PT_UNICODE, pidProfileMin+0x2a)
#define	PR_PROFILE_SERVER_FQDN_W				PROP_TAG( PT_UNICODE, pidProfileMin+0x2b)
#define PR_PROFILE_ALTERNATE_STORE_TYPE PROP_TAG(PT_UNICODE, 0x65D0)
#ifndef CONFIG_OST_CACHE_PRIVATE
#define CONFIG_OST_CACHE_PRIVATE			((ULONG)0x00000180)
#endif
#ifndef CONFIG_OST_CACHE_DELEGATE_PIM
#define CONFIG_OST_CACHE_DELEGATE_PIM		((ULONG)0x00000800)
#endif
#ifndef CONFIG_OST_CACHE_PUBLIC
#define CONFIG_OST_CACHE_PUBLIC				((ULONG)0x00000400)
#endif
#define CONNECT_IGNORE_NO_PF			((ULONG)0x8000)


